In [54]:
#### ndarray 属性
import numpy as np
a = np.array([[1,2,1],[3,4,5]])
print(a.ndim) # 秩，即轴的数量或者维度的数量
print(a.shape) # 数组的维度，对于矩阵 n 行 m 列
print(a.size) # n * m ，即元素个数
print(a.dtype) # 元素类型
print(a.itemsize) # 元素的大小，以字节为单位
a.shape = (3,2)
print(a)
b = a.reshape(3,2,1)
print(b)
print(a[a>2])
print(a[~np.isnan(a)]) # 过滤 NaN
print(a[[1,0]])
print(a[[-1,-2]])
np.save("a.npy",a)
aa=np.load("a.npy")
print(aa.shape)

2
(2, 3)
6
int32
4
[[1 2]
 [1 3]
 [4 5]]
[[[1]
  [2]]

 [[1]
  [3]]

 [[4]
  [5]]]
[3 4 5]
[1 2 1 3 4 5]
[[1 3]
 [1 2]]
[[4 5]
 [1 3]]
(3, 2)


In [60]:
n = np.arange(24).reshape(2,-1,2,2) # -1 自动补全，等于 24/2/2/2
print(n)
n.shape

[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]

  [[ 8  9]
   [10 11]]]


 [[[12 13]
   [14 15]]

  [[16 17]
   [18 19]]

  [[20 21]
   [22 23]]]]


(2, 3, 2, 2)

In [64]:
print(np.zeros(11)) # 0 数组
print(np.empty(11)) # 空数组

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [77]:
import numpy as np
mx1 = np.random.randint(-1,3,(2,2))
mx2 = np.array([[1,2],[2,3]])

result = np.zeros((mx1.shape[0], mx2.shape[1])) # shape[0]代表行数 shape[1]代表列数

# 外层的两个循环用来遍历结果矩阵的每一个位置，而内层的循环用来计算每一个位置的值
for i in range(mx1.shape[0]):
    for j in range(mx2.shape[1]):
        for k in range(mx1.shape[1]):
            result[i,j] += mx1[i,k] * mx2[k,j]
print(result)

[[4. 7.]
 [2. 3.]]
[[4 7]
 [2 3]]


In [ ]:
import numpy as np

# 生成从1到99的奇数序列
t4_odd_nums = np.arange(1, 100, 2)
# print(odd_nums)

# 计算奇数序列的倒数并相加
t4_sum = 0
for i in t4_odd_nums:
    t4_sum += 1.0/i

print(f"和为: {t4_sum:.4f}")