<!--
模板使用方法：将此代码块转为Markdown块然后点击左侧三角渲染（依赖 jupyter-wysiwyg ）
模板参数说明：将超链接的路径替换即可
@hyperlink_1: href="https://github.com/{组织或用户}/{仓库}/blob/{分支}/{目录和文件名组成的路径}"
@hyperlink_2: href="https://nbviewer.org/github/{组织或用户}/{仓库}/blob/{分支}/{目录和文件名组成的路径}"
注意事项：在 <p>...</p> 中添加注释或者空行等行为会破坏渲染效果
-->

<!-- start of template header -->
<p>
<div style="display:flex">
<a alt="hyperlink_1" title="在Github查看当前文件" href="https://github.com/Soltus/learn-python-BI/blob/main/lesson1/%E5%A4%A7%E6%95%B0%E6%8D%AE%E6%8A%80%E6%9C%AF%E8%AF%BE%E5%86%85%E5%AE%9E%E9%AA%8C/%E5%AE%9E%E9%AA%8C%E4%BA%8C-NumPy%E7%BB%83%E4%B9%A0.ipynb" target="_blank"><img src="https://img.shields.io/badge/File-black?logo=github" style="height: 38px"/></a>
<span style="width:5.8px"></span>
<a alt="hyperlink_2" title="在nbviewer查看当前文件" href="https://nbviewer.org/github/Soltus/learn-python-BI/blob/main/lesson1/%E5%A4%A7%E6%95%B0%E6%8D%AE%E6%8A%80%E6%9C%AF%E8%AF%BE%E5%86%85%E5%AE%9E%E9%AA%8C/%E5%AE%9E%E9%AA%8C%E4%BA%8C-NumPy%E7%BB%83%E4%B9%A0.ipynb" target="_blank"><img src="https://img.shields.io/badge/nbviewer-white?logo=jupyter" style="height: 38px"/></a>
</div>
</p>

<!-- 避免二次渲染当前块 -->
<!-- 请勿在此处添加内容 -->
<!-- end of template header -->

<h2 class="MsoNormal"><span class="15" style="font-family: 'Times New Roman'; font-size: 24pt; color: #b96ad9;">题一</span></h2>
<blockquote><span class="15" style="font-family: 'Times New Roman'; font-size: 12pt;">用单纯形法求解以下线性规划问题：</span></blockquote>

$$\max z=50x_1+100x_2$$ $$s.t.\qquad\begin{split}x_1+x_2\leq300\\2x_1+x_2\leq400\\x_2\leq250\\x_1,x_2\geq0\end{split}$$

<h2>（1）首先化为标准形式，声明变量且赋值为Numpy对象：</h2>

<p>$$\max z=50x_1+100x_2$$ $$s.t.\qquad\begin{split}x_1+x_2+x_3=300\\2x_1+x_2+x_4=400\\x_2+x_5=250\\x_1,x_2,x_3,x_4,x_5\geq0\end{split}$$</p>

In [8]:
t1_c = np.array([-50, -100, 0, 0, 0]).reshape(-1, 1) # 如果等于-1的话，那么Numpy会根据剩下的维度计算出数组的另外一个shape属性值
t1_A = np.array([[1, 1, 1, 0, 0], [2, 1, 0, 1, 0],[0, 1, 0, 0, 1]])
t1_b = np.array([300, 400, 250]).reshape(-1, 1)

<h2>（2）接着定义求解函数 <code>simplex</code>：</h2>

In [12]:
import numpy as np # 使用 np 作为别名
# np.matmul 求两个数组的矩阵乘积 ref: https://numpy.org/doc/stable/reference/generated/numpy.matmul.html
# np.linalg.inv 计算矩阵的（乘法）逆运算 ref: https://numpy.org/doc/stable/reference/generated/numpy.linalg.inv.html

def myMatmul(a, b):
    ''' 使用教材的方式实现 np.matmul '''
    kk = []
    for i in range(a.shape[0]):
        k = []
        for j in range(b.shape[1]):
            k.append(sum(a[i,...]*b[...,j]))
        kk.append(k)
    return np.array(kk)

def simplex(c,A,b):
    ''' 求解函数 '''
    # 当输入的c,A,b有缺失值时，输出错误原因，函数执行结束
    if c.shape[0] != A.shape[1]:
        print("A和C形状不匹配")
        return 0
    if b.shape[0] != A.shape[0]:
        print("A和b形状不匹配")
        return 0
    num=A.shape[1]-A.shape[0]
    N_indexs=np.arange(0,num) # 非基变量的下标索引
    B_indexs=np.arange(num,A.shape[1]) # 基变量的下标索引
    N=A[:,N_indexs] # 初始的 N
    B=A[:,B_indexs] # 初始的 B
    c_N=c[N_indexs,:]
    c_B=c[B_indexs,:]
    # x_B = np.matmul(np.linalg.inv(B), b)
    x_B = myMatmul(np.linalg.inv(B), b)
    i=0
    while 1:
        # 判断r值是否>=0，若r的每一维都>=0，则满足最优化条件。若r中有值<0，则继续寻找最优点。
        R=(c_N.T - np.matmul(np.matmul(c_B.T, np.linalg.inv(B)), N)).flatten()
        if all(R >= 0):
            print("##########################找到最优点##########################")
            print("非基变量的索引为",N_indexs)
            print("基变量的索引为",B_indexs)
            print("最优点为",x_B.flatten())
            print("最优值为",z.flatten()[0])
            return 0
        else:
            i=i+1
            print("step",i)
            # 找到入基变量
            N_in_index = np.argmin(R)  # 找到入基变量的下标
            N_in=N[:,N_in_index] # 入基变量对应的Aq
            # 找到出基变量
            negd=np.matmul(np.linalg.inv(B),N_in)
            y=x_B.flatten()/negd
            # 设置一个初值索引index，需满足negd[index]>0
            for i in range(len(y)):
                if negd[i]>0:
                    index=i
                    break
            # 找到y最小且negd>0的位置
            for i in range(len(y)):
                if negd[i]<=0:
                    continue
                elif y[i]<y[index]:
                    index=i
            B_out_index=index # 找到出基变量的下标
            B_out=B[:,B_out_index] # 出基变量对应的Aq
            #出入基变量交换位置
            in_index=N_indexs[N_in_index]
            out_index=B_indexs[B_out_index]
            temp=N_indexs[N_in_index]
            N_indexs[N_in_index]=B_indexs[B_out_index]
            B_indexs[B_out_index]=temp
            N[:,N_in_index]=B_out
            B[:,B_out_index]=N_in
            c_N = c[N_indexs, :]
            c_B = c[B_indexs, :]
            N = A[:, N_indexs]
            B = A[:, B_indexs]
            x_B = np.matmul(np.linalg.inv(B), b)
            z = np.matmul(c_B.T, x_B)
            print("出基变量索引",out_index)
            print("入基变量索引",in_index)
            print("值为",z.flatten()[0])


<h2>（3）最后使用函数求解问题：</h2>

In [13]:
simplex(t1_c,t1_A,t1_b)

step 1
出基变量索引 4
入基变量索引 1
值为 -25000.0
step 3
出基变量索引 2
入基变量索引 0
值为 -27500.0
##########################找到最优点##########################
非基变量的索引为 [2 4]
基变量的索引为 [0 3 1]
最优点为 [ 50.  50. 250.]
最优值为 -27500.0


C:\Windows\Temp\ipykernel_24520\999845842.py:52: RuntimeWarning: divide by zero encountered in divide
  y=x_B.flatten()/negd


0

<h1><span class="15" style="font-family: 'Times New Roman'; font-size: 24pt; color: #b96ad9;">题二</span></h1>
<blockquote><span class="15" style="font-family: 'Times New Roman'; font-size: 12pt;">求下列矩阵的逆矩阵</span></blockquote>
<p><span class="15" style="font-family: 'Times New Roman'; font-size: 12pt;"><span style="font-family: 'Microsoft YaHei'; font-size: medium;">$$Array_1=np.array([1,1,1],[0,2,5],[2,5,-1])$$</span></span></p>
<p>&nbsp;</p>

<h1><span style="color: #b96ad9;">题三</span></h1>
<blockquote>
<p>使用Numpy数组对象，创建两个3*3的矩阵，并计算矩阵乘积。</p>
</blockquote>

In [49]:
import numpy as np

# 创建两个3*3的矩阵
t3_matrix1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
t3_matrix2 = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

# 计算矩阵乘积
matrix_product = np.dot(t3_matrix1, t3_matrix2)

# 输出结果
print(matrix_product)

[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [51]:
# 计算矩阵乘积
matrix_product2 = myMatmul(t3_matrix1, t3_matrix2) # myMatmul 在题一中定义

# 输出结果是一样的
print(matrix_product2)

[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


<p><span style="font-size: 14pt;"><code>np.dot</code> 和 <code>np.matmul</code> 都是矩阵乘法，在矢量乘矢量的內积运算中没有区别，但是 <code>np.matmul</code> 无法用于标量与array相乘。在两个 array 的维度均 <span style="color: #169179;"><span style="color: #f1c40f;">n&gt;2</span> </span>的情况下， <code>np.matmul()</code> 是对应位置的矩阵分别作点积，而 <code>np.dot()</code> 是 arrayA 的所有矩阵都与 arrayB 的所有矩阵作点积。</span></p>

<h1><span style="color: #b96ad9;">题四</span></h1>
<blockquote>
<p>计算 $1+1/3+1/5+1/7+\quad ... \quad +1/99$ 的和。</p>
</blockquote>

In [45]:
import numpy as np

# 生成从1到99的奇数序列
t4_odd_nums = np.arange(1, 100, 2)
# print(odd_nums)

# 计算奇数序列的倒数并相加
# t4_sum = np.sum(1.0/t4_odd_nums)
t4_sum = 0
for i in t4_odd_nums:
    t4_sum += 1.0/i

print(f"和为: {t4_sum:.4f}")

和为: 2.9378


<h1><span style="color: #b96ad9;">题五</span></h1>
<blockquote>
<p>对一个 5 &times; 5 的随机矩阵做归一化（可选择不同归一化方法）。</p>
</blockquote>

<h1><span style="color: #b96ad9;">题六</span></h1>
<blockquote>
<p>选取三种排序算法（冒泡排序除外），对列表排序。</p>
</blockquote>

In [14]:
import numpy as np

def quick_sort(arr):
    '''快速排序（QuickSort）'''
    if len(arr) <= 1:
        return arr
    pivot = arr[0]
    left = np.array([x for x in arr[1:] if x < pivot])
    right = np.array([x for x in arr[1:] if x >= pivot])
    return np.concatenate((quick_sort(left), [pivot], quick_sort(right)))

def merge_sort(arr):
    '''归并排序（Merge Sort）'''
    if len(arr) <= 1:
        return arr
    mid = len(arr) // 2
    left = merge_sort(arr[:mid])
    right = merge_sort(arr[mid:])
    i = j = 0
    result = np.empty(len(arr), dtype=arr.dtype)
    while i < len(left) and j < len(right):
        if left[i] < right[j]:
            result[i+j] = left[i]
            i += 1
        else:
            result[i+j] = right[j]
            j += 1
    result[i+j:] = left[i:] if i < len(left) else right[j:]
    return result

def heap_sort(arr):
    '''堆排序（Heap Sort）'''
    def sift_down(arr, start, end):
        root = start
        while True:
            child = 2 * root + 1
            if child > end:
                break
            if child + 1 <= end and arr[child] < arr[child + 1]:
                child += 1
            if arr[root] < arr[child]:
                arr[root], arr[child] = arr[child], arr[root]
                root = child
            else:
                break
    # Build Max-Heap
    for start in range((len(arr)-2)//2, -1, -1):
        sift_down(arr, start, len(arr)-1)
    # Heap Sort
    for end in range(len(arr)-1, 0, -1):
        arr[0], arr[end] = arr[end], arr[0]
        sift_down(arr, 0, end-1)
    return arr


In [24]:
import random

my_list = [random.randint(1, 100) for _ in range(10)]
my_list = np.array(my_list)
print('原列表  ',my_list)

t6_s1 = quick_sort(my_list)
t6_s2 = merge_sort(my_list)
t6_s3 = heap_sort(my_list)
print('快速排序',t6_s1)
print('归并排序',t6_s2)
print('堆排序  ',t6_s3)

原列表   [ 4 44 67 66 86  8 34 31 85 48]
快速排序 [ 4.  8. 31. 34. 44. 48. 66. 67. 85. 86.]
归并排序 [ 4  8 31 34 44 48 66 67 85 86]
堆排序   [ 4  8 31 34 44 48 66 67 85 86]


<!-- start of template footer -->
<p>
<div style="display:flex">
<a href="tencent://AddContact/?fromId=45&fromSubId=1&subcmd=all&uin=694357845&website=www.oicqzone.com" target="_blank"><img title="添加QQ好友" src="https://img.shields.io/badge/QQ-694357845-blue?logo=Tencent QQ" style="height: 38px"/></a>
</div>
</p>
<!-- end of template footer -->