In [1]:
import numpy as np 
a = np.array([1,2,3]) 
print (a)

[1 2 3]


In [2]:
# 多于一个维度 
import numpy as np 
a = np.array([[1, 2], [3, 4]]) 
print (a)

[[1 2]
 [3 4]]


In [3]:
# 最小维度 
import numpy as np 
a = np.array([1, 2, 3,4,5], ndmin = 2) 
print (a)

[[1 2 3 4 5]]


In [4]:
# dtype 参数 
import numpy as np 
a = np.array([1, 2, 3], dtype = complex) 
print (a)

[1.+0.j 2.+0.j 3.+0.j]


In [10]:
import numpy as np  
A = np.arange(5)  # 只有结束项
A 

array([0, 1, 2, 3, 4])

In [11]:
A.dtype

dtype('int32')

In [12]:
A = np.arange(1, 5)  # 起点为1，步长默认为1
A

array([1, 2, 3, 4])

In [13]:
A = np.arange(1, 5, 2)  # 步长默认为2
A

array([1, 3])

In [14]:
A = np.arange(1, 5.2, 0.6)  # 浮点数参数，结果就不一定完全符合了
A

array([1. , 1.6, 2.2, 2.8, 3.4, 4. , 4.6, 5.2])

In [5]:
import numpy as np  
a = np.arange(24)  
print (a.ndim)             # a 现只有一个维度
a

1


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [6]:
# 现在调整其大小
b = a.reshape(2,4,3)  # b 现在拥有三个维度
print (b.ndim)

3


In [7]:
b

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [8]:
import numpy as np   
a = np.array([[1,2,3],[4,5,6]])  
print (a.shape)

(2, 3)


In [9]:
import numpy as np  
a = np.array([[1,2,3],[4,5,6]]) 
a.shape =  (3,2)  
print (a)

[[1 2]
 [3 4]
 [5 6]]


In [15]:
a = [1, 2, 3, 4]
b = a
a

[1, 2, 3, 4]

In [16]:
b

[1, 2, 3, 4]

In [17]:
a[0] = 0
a

[0, 2, 3, 4]

In [18]:
b

[0, 2, 3, 4]

In [19]:
a = [1, 2, 3, 4]
b = a.copy()
a, b

([1, 2, 3, 4], [1, 2, 3, 4])

In [20]:
a[0] = 0
a, b

([0, 2, 3, 4], [1, 2, 3, 4])